<Project Sdk="Godot.NET.Sdk/4.7.2">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <RootNamespace>OpenRanch.Game</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\OpenRanch.Formats\OpenRanch.Formats.csproj" />
    <ProjectReference Include="..\src\OpenRanch.Simulation\OpenRanch.Simulation.csproj" />
    <ProjectReference Include="..\src\OpenRanch.Ranch\OpenRanch.Ranch.csproj" />
  </ItemGroup>

</Project>
